namespace SpriteKind {
    export const PhysicsEnabled = SpriteKind.create()
    export const hidden = SpriteKind.create()
    export const Block = SpriteKind.create()
}
sprites.onDestroyed(SpriteKind.Block, function (sprite) {
    info.changeScoreBy(1)
    PingPong_Ball.setVelocity(randint(-50, 50), 50)
})
sprites.onOverlap(SpriteKind.PhysicsEnabled, SpriteKind.Player, function (sprite, otherSprite) {
    moveRandom(PingPong_Ball)
})
sprites.onOverlap(SpriteKind.PhysicsEnabled, SpriteKind.Block, function (sprite, otherSprite) {
    otherSprite.destroy()
})
sprites.onOverlap(SpriteKind.PhysicsEnabled, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
})
info.onLifeZero(function () {
    game.over(false)
})
function moveRandom (mySprite: Sprite) {
    mySprite.setVelocity(randint(-50, 50), -50)
}
let PingPong_Ball: Sprite = null
let PlayerSpr = sprites.create(assets.image`PaddleTXTR`, SpriteKind.Player)
controller.moveSprite(PlayerSpr, 100, 0)
PlayerSpr.setStayInScreen(true)
PlayerSpr.setPosition(80, 100)
PingPong_Ball = sprites.create(assets.image`ballTXTR`, SpriteKind.PhysicsEnabled)
PingPong_Ball.setBounceOnWall(true)
PingPong_Ball.setVelocity(0, 50)
info.setLife(1)
info.setScore(0)
let deth1 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth1.setPosition(5, 110)
let deth2 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth2.setPosition(15, 110)
let deth3 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth3.setPosition(25, 110)
let deth4 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth4.setPosition(35, 110)
let deth5 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth5.setPosition(45, 110)
let deth6 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth6.setPosition(55, 110)
let deth7 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth7.setPosition(65, 110)
let deth8 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth8.setPosition(75, 110)
let deth9 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth9.setPosition(85, 110)
let deth10 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth10.setPosition(95, 110)
let deth11 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth11.setPosition(105, 110)
let deth12 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth12.setPosition(115, 110)
let deth13 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth13.setPosition(125, 110)
let deth14 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth14.setPosition(135, 110)
let deth15 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth15.setPosition(145, 110)
let deth16 = sprites.create(assets.image`dethTXTR`, SpriteKind.Enemy)
deth16.setPosition(155, 110)
let block1 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block1.setPosition(16, 16)
scaling.scaleByPixels(PingPong_Ball, -5, ScaleDirection.Uniformly, ScaleAnchor.Middle)
scaling.scaleByPixels(block1, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block2 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block2.setPosition(16, 32 + 16)
scaling.scaleByPixels(block2, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block3 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block3.setPosition(16 + 16 + 16, 16)
scaling.scaleByPixels(block3, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block4 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block4.setPosition(32 + 16, 32 + 16)
scaling.scaleByPixels(block4, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block5 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block5.setPosition(64 + 16, 16)
scaling.scaleByPixels(block5, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block6 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block6.setPosition(64 + 32 + 16, 16)
scaling.scaleByPixels(block6, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block7 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block7.setPosition(64 + 32 + 16, 32 + 16)
scaling.scaleByPixels(block7, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block8 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block8.setPosition(64 + 32 + 32 + 16, 16)
scaling.scaleByPixels(block8, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let block9 = sprites.create(assets.image`blockTXTR`, SpriteKind.Block)
block9.setPosition(64 + 32 + 32 + 16, 32 + 16)
scaling.scaleByPixels(block9, 10, ScaleDirection.Uniformly, ScaleAnchor.Middle)
game.onUpdate(function () {
    if (info.score() >= 9) {
        game.over(true)
    }
})
